baseURL = 'http://hommel.lt/'
languageCode = 'en-us'
title = 'Lt. Hommel'
theme = "ananke"

[params]
  author = "Mina"
  email = "bzzz@hommel.lt"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
